INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('John', 'Doe', 45);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Vasya', 'Jun', 23);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Petya', 'Petrov', 32);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Peter', 'Jupiter', 18);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Kate', 'Travolta', 64);