CREATE TABLE USERS(
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    AGE NUMBER
);

CREATE TABLE PRODUCTS(
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(56) NOT NULL,
    PRICE NUMBER NOT NULL,
    CATEGORY VARCHAR(12) NOT NULL,
    GENDER VARCHAR(6) NOT NULL,
    COLOR VARCHAR(18) NOT NULL,
    PRODUCT_SIZE VARCHAR(2) NOT NULL,
    REMAINING_COUNT VARCHAR(2) NOT NULL
);
