CREATE TABLE USERS(
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    AGE NUMBER
);

CREATE TABLE PRODUCTS(
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(56) NOT NULL,
    PRICE NUMBER NOT NULL,
    CATEGORY VARCHAR(12) NOT NULL,
    GENDER VARCHAR(6) NOT NULL,
    COLOR VARCHAR(18) NOT NULL,
    PRODUCT_SIZE VARCHAR(2) NOT NULL,
    REMAINING_COUNT VARCHAR(2) NOT NULL
);

CREATE TABLE ORDERS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID NUMBER NOT NULL,
    STATUS VARCHAR (32) NOT NULL,
    CREATION_DATE DATE,
    CONSTRAINT USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ORDERS_PRODUCTS (
    ORDER_ID NUMBER NOT NULL,
    PRODUCTS_ID NUMBER NOT NULL,
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCTS_ID) REFERENCES PRODUCTS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);